plugins {
	id 'maven-publish'
	alias libs.plugins.quilt.loom
}

group = project.maven_group
version = "${project.mod_version}+minecraft-${libs.versions.minecraft.get()}"

base {
	archivesName = project.archives_base_name
}

repositories {
	// Add repositories to retrieve artifacts from in here.
	// You should only use this when depending on other mods because
	// Loom adds the essential maven repositories to download Minecraft and libraries from automatically.
	// See https://docs.gradle.org/current/userguide/declaring_repositories.html
	// for more information about repositories.
	maven { url 'https://maven.nucleoid.xyz' }
}

// All the dependencies are declared at gradle/libs.version.toml and referenced with "libs.<id>"
// See https://docs.gradle.org/current/userguide/platforms.html for information on how version catalogs work.
dependencies {
	minecraft libs.minecraft
	mappings loom.officialMojangMappings()

	modImplementation libs.quilt.loader
	modImplementation include(libs.polymer.get())
}

processResources {
	inputs.property 'version', project.mod_version

	filesMatching('quilt.mod.json') {
		expand "version": project.mod_version
	}
}

java {
	withSourcesJar()

	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.encoding = "UTF-8"

	javaCompiler = javaToolchains.compilerFor {
		languageVersion = JavaLanguageVersion.of(21)
	}
}


// If you plan to use a different file for the license, don't forget to change the file name here!
jar {
	from('LICENSE') {
		rename { "${it}_${project.archives_base_name}" }
	}
}
