[versions]
# The latest versions are available at https://lambdaurora.dev/tools/import_quilt.html
minecraft = "1.21.1"

quilt_loader = "0.26.0"
polymer = "0.9.11+1.21.1"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }

polymer = { module = "eu.pb4:polymer-core", version.ref = "polymer" }
quilt_loader = { module = "org.quiltmc:quilt-loader", version.ref = "quilt_loader" }

# If you have multiple similar dependencies, you can declare a dependency bundle and reference it on the build script with "libs.bundles.example".
[bundles]

[plugins]
quilt_loom = { id = "org.quiltmc.loom", version = "1.7.4" }
